#!/usr/bin/env python3
"""
tax_log.py

Daily tax-SETTLEMENT snapshot for Irish-owned factories abroad.

This is not a tax-statistics logger. It is a settlement logger: for every
country that hosts Irish-owned factories it records how much that country
owes Ireland under the negotiated rebate agreement in data/tax/deals.json.

Run once per day (GitHub Actions). Mirrors the logic in js/irish-tax(-dev).js
but writes to disk so we can track daily rebate + weekly settlement trends.

Pipeline (same as the browser tool):
  1. Paginate all Irish citizens.
  2. worker.getWorkers per citizen → factories they OWN that have workers.
  3. company.getById → region → country (regionsObject) → income-tax rate.
  4. transaction.getPaginatedTransactions (wage, last 24h) → wages the owner
     actually paid, bucketed PER WORKER (so tax can be split by citizenship).
  5. user.getUserLite per worker → citizenship (Irish vs non-Irish).
  6. Per worker: tax = wages × rate / 100. Manual rebate owed to Ireland =
     tax × irishRebate (Irish worker) or tax × foreignRebate (non-Irish),
     using the host country's agreement. Aggregated per country.

SETTLEMENT MODEL (see data/tax/deals.json):
  The game AUTOMATICALLY remits 30% of every worker's income tax to that
  worker's citizenship country. That automatic transfer is a game mechanic
  and is NEVER part of the settlement. Agreements define only the additional
  MANUAL rebate the host government pays Ireland. So the settlement figure
  for a country is purely  Σ(worker tax × that worker's rebate rate).

STORAGE:
  data/tax/deals.json          — the (data-driven) agreement config
  data/tax/current_week.json   — rolling Mon–Sun log; resets each Monday
  data/tax/weeks/YYYY-MM-DD.json — archived completed weeks (named by Monday)

current_week.json shape (per-country day/total entry):
  { "id": "...", "name": "...", "code": "ie", "rate": 10.0,
    "factories": 3, "workers": 12,
    "irish_workers": 4, "foreign_workers": 8,
    "wages": 5000.0,
    "tax": 500.0,                 ← GROSS tax generated (Irish + foreign)
    "irish_worker_tax": 180.0,    ← gross tax generated by Irish workers
    "foreign_worker_tax": 320.0,  ← gross tax generated by non-Irish workers
    "manual_rebate_due": 165.0,   ← settlement owed to Ireland (the number that matters)
    "host_retained": 185.0,       ← gross − automatic 30% − manual rebate
    "irish_rebate": 0.25,         ← this country's Irish-worker rebate rate (from deals.json)
    "foreign_rebate": 0.375,      ← this country's non-Irish-worker rebate rate (from deals.json)
    "deal_version": 1 }           ← deals.json version in force when logged

Gross tax stored (not just the rebate) so historical settlements can be
recalculated if an agreement changes. Tax figures are ESTIMATES: wage
transactions carry no tax line, so we apply the factory-country's current
income-tax rate to the wages actually paid.
"""

import json
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
PROXY_BASE         = "https://warera-proxy.0x5ca1ab1e.workers.dev/trpc"
ORIGIN             = "https://we.hawtre.net"
IRELAND_COUNTRY_ID = "6813b6d446e731854c7ac7fe"
ROOT               = Path(__file__).parent
TAX_DIR            = ROOT / "data" / "tax"
WEEKS_DIR          = TAX_DIR / "weeks"
CURRENT_WEEK_FILE  = TAX_DIR / "current_week.json"
DEALS_FILE         = TAX_DIR / "deals.json"
HTTP_TIMEOUT       = 30
MAX_RETRIES        = 3
RETRY_BACKOFF      = 4      # seconds × attempt number
USER_AGENT         = "warera-tax-log/1.0"
PAGE_LIMIT         = 100
WORKERS            = 8      # concurrent factory/wage fetches
COUNTRY_WORKERS    = 20     # more parallelism for country lookups (cheap calls)
WAGE_WINDOW_H      = 24
WAGE_MAX_PAGES     = 5
AUTO_REMIT         = 0.30  # game mechanic: 30% of every worker's income tax is auto-remitted to
                           # their citizenship country. NOT part of the settlement — only used to
                           # derive host_retained (gross − auto-remit − manual rebate).


# ── HTTP / tRPC helpers ───────────────────────────────────────────────────────

def log(msg):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def http_get_json(url):
    last_err = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers={
                "User-Agent": USER_AGENT,
                "Origin":     ORIGIN,
                "Accept":     "application/json",
            })
            with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT) as r:
                return json.loads(r.read().decode("utf-8"))
        except (urllib.error.URLError, urllib.error.HTTPError,
                json.JSONDecodeError, TimeoutError) as e:
            last_err = e
            if attempt < MAX_RETRIES:
                time.sleep(RETRY_BACKOFF * attempt)
    raise RuntimeError(f"GET failed after {MAX_RETRIES} attempts: {last_err}")


def trpc_raw(method, payload):
    """Return the full decoded JSON envelope (not just result.data)."""
    inp = urllib.parse.quote(json.dumps(payload, separators=(",", ":")))
    return http_get_json(f"{PROXY_BASE}/{method}?input={inp}")


def trpc(method, payload):
    return (trpc_raw(method, payload) or {}).get("result", {}).get("data")


# ── Deal (agreement) config ───────────────────────────────────────────────────

DEFAULT_DEAL = {"irishRebate": 0.0, "foreignRebate": 0.0}


def load_deals():
    """
    Load data/tax/deals.json → (version:int, by_code:dict, default:dict).
    Data-driven: no country-specific logic lives in this file. A missing or
    malformed deals file falls back to "no agreements" (all rebates 0) rather
    than aborting the run — a settlement of 0 is correct when no deal exists.
    """
    try:
        with DEALS_FILE.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        log(f"WARN: could not load {DEALS_FILE.name} ({e}) — defaulting to no agreements")
        return 0, {}, dict(DEFAULT_DEAL)
    version = int(data.get("version", 0))
    default = {**DEFAULT_DEAL, **(data.get("default") or {})}
    by_code = {}
    for code, deal in (data.get("countries") or {}).items():
        by_code[str(code).upper()] = {
            "irishRebate":   float(deal.get("irishRebate",   default["irishRebate"])),
            "foreignRebate": float(deal.get("foreignRebate", default["foreignRebate"])),
        }
    log(f"loaded deals v{version}: {len(by_code)} agreement(s)")
    return version, by_code, default


def deal_for(code, by_code, default):
    """Look up a country's agreement by ISO code (case-insensitive). No match → default."""
    if not code:
        return default
    return by_code.get(str(code).upper(), default)


# ── API calls ─────────────────────────────────────────────────────────────────

def fetch_all_irish():
    """Paginate user.getUsersByCountry → list of {_id, username} dicts."""
    items, cursor, safety = [], None, 0
    while safety < 300:
        inp = {"countryId": IRELAND_COUNTRY_ID, "limit": PAGE_LIMIT}
        if cursor:
            inp["cursor"] = cursor
        if safety == 0:
            # First page: fetch raw so we can dump the envelope if it's empty.
            raw = trpc_raw("user.getUsersByCountry", inp)
            page = (raw or {}).get("result", {}).get("data")
            first_arr = (page.get("items") if isinstance(page, dict)
                         else (page if isinstance(page, list) else []))
            if not first_arr:
                log("DIAG: first getUsersByCountry page returned no items.")
                log(f"DIAG: raw envelope (first 800 chars): "
                    f"{json.dumps(raw)[:800] if raw is not None else 'None'}")
        else:
            page = trpc("user.getUsersByCountry", inp)
        arr = (page.get("items") if isinstance(page, dict)
               else (page if isinstance(page, list) else []))
        items.extend(arr or [])
        nxt = (page.get("nextCursor") or page.get("cursor")) if isinstance(page, dict) else None
        if not nxt or not arr:
            break
        cursor = nxt
        safety += 1
    return items


def fetch_worker_entries(cid):
    """
    Call worker.getWorkers for one citizen and return a list of factory entries:
      [{ compId, compName, itemCode, ownerId, workers: [userId, ...] }, ...]
    Returns [] on error or if they own no factories with workers.
    """
    try:
        res = trpc("worker.getWorkers", {"userId": cid})
    except Exception as e:
        log(f"  getWorkers error for {cid}: {e}")
        return []

    wpc = (res or {}).get("workersPerCompany") or []
    entries = []
    for entry in wpc:
        co      = entry.get("company")
        comp_id = (co.get("_id") if isinstance(co, dict)
                   else (co if isinstance(co, str) else None))
        workers_raw = entry.get("workers") or []
        if not comp_id or not workers_raw:
            continue
        wids = []
        for w in workers_raw:
            uid = (w.get("user") or w.get("_id") if isinstance(w, dict)
                   else (w if isinstance(w, str) else None))
            if uid:
                wids.append(uid)
        if wids:
            entries.append({
                "compId":   comp_id,
                "compName": co.get("name") if isinstance(co, dict) else None,
                "itemCode": co.get("itemCode") if isinstance(co, dict) else None,
                "ownerId":  cid,
                "workers":  wids,
            })
    return entries


def fetch_company_country(comp_id, regions_obj):
    """company.getById → region → countryId.  Returns (comp_id, countryId|None)."""
    try:
        co = trpc("company.getById", {"companyId": comp_id})
    except Exception:
        return comp_id, None
    if not isinstance(co, dict):
        return comp_id, None
    region = regions_obj.get(co.get("region"))
    return comp_id, (region.get("country") if isinstance(region, dict) else None)


def fetch_wages_paid(owner_id, worker_to_comp):
    """
    Scan owner's wage transactions for the last 24h.
    Returns { workerId: total_wages_paid } — bucketed PER WORKER so tax can
    later be split by each worker's citizenship. Only workers that map to one
    of this owner's factories (present in worker_to_comp) are counted.
    """
    cutoff_ts = datetime.now(timezone.utc).timestamp() - WAGE_WINDOW_H * 3600
    by_worker = {}
    cursor, pages, stop = None, 0, False

    while pages < WAGE_MAX_PAGES and not stop:
        inp = {"userId": owner_id, "transactionType": "wage", "limit": 100}
        if cursor:
            inp["cursor"] = cursor
        try:
            page = trpc("transaction.getPaginatedTransactions", inp)
        except Exception:
            break
        if not isinstance(page, dict):
            break

        items = page.get("items") or page.get("data") or []
        for tx in items:
            created = tx.get("createdAt")
            if not created:
                continue
            try:
                tx_ts = datetime.fromisoformat(
                    created.replace("Z", "+00:00")
                ).timestamp()
            except Exception:
                continue
            if tx_ts < cutoff_ts:
                stop = True
                continue
            if tx.get("buyerId") != owner_id:
                continue
            worker_id = tx.get("sellerId")
            if worker_id in worker_to_comp:
                by_worker[worker_id] = by_worker.get(worker_id, 0) + (tx.get("money") or 0)

        cursor = page.get("nextCursor")
        pages += 1
        if not cursor or not items:
            break

    return by_worker


def fetch_user_country(uid):
    """user.getUserLite → (userId, citizenshipCountryId|None). Used to split
    each worker's tax into Irish vs non-Irish for the settlement calc."""
    try:
        u = trpc("user.getUserLite", {"userId": uid})
    except Exception:
        return uid, None
    if not isinstance(u, dict):
        return uid, None
    return uid, (u.get("country") or u.get("countryId"))


# ── Weekly log helpers ────────────────────────────────────────────────────────

def this_weeks_monday(today: date) -> date:
    """Monday of the Mon–Sun game week that contains today."""
    return today - timedelta(days=today.weekday())


def recalc_totals(days):
    """
    Sum per-country figures across all day entries in the week.
    Returns a dict { countryId: {...} }.
    Re-computed from scratch each save so it stays consistent even if a
    day entry was replaced by a later re-run. `.get(..., 0)` on the split
    fields keeps pre-settlement day entries (logged before this schema) from
    breaking the sum — they simply contribute 0 rebate.
    """
    totals = {}
    for day in days:
        for c in day.get("countries", []):
            cid = c["id"]
            if cid not in totals:
                totals[cid] = {
                    "name":               c["name"],
                    "code":               c.get("code"),
                    "rate":               c["rate"],
                    "factories":          0,
                    "workers":            0,
                    "irish_workers":      0,
                    "foreign_workers":    0,
                    "wages":              0.0,
                    "tax":                0.0,
                    "irish_worker_tax":   0.0,
                    "foreign_worker_tax": 0.0,
                    "manual_rebate_due":  0.0,
                    "host_retained":      0.0,
                    "irish_rebate":       c.get("irish_rebate", 0.0),
                    "foreign_rebate":     c.get("foreign_rebate", 0.0),
                    "deal_version":       c.get("deal_version", 0),
                }
            t = totals[cid]
            t["factories"]          += c.get("factories", 0)
            t["workers"]            += c.get("workers", 0)
            t["irish_workers"]      += c.get("irish_workers", 0)
            t["foreign_workers"]    += c.get("foreign_workers", 0)
            t["wages"]               = round(t["wages"]              + c.get("wages", 0.0), 2)
            t["tax"]                 = round(t["tax"]                + c.get("tax", 0.0), 2)
            t["irish_worker_tax"]    = round(t["irish_worker_tax"]   + c.get("irish_worker_tax", 0.0), 2)
            t["foreign_worker_tax"]  = round(t["foreign_worker_tax"] + c.get("foreign_worker_tax", 0.0), 2)
            t["manual_rebate_due"]   = round(t["manual_rebate_due"]  + c.get("manual_rebate_due", 0.0), 2)
            t["host_retained"]       = round(t["host_retained"]      + c.get("host_retained", 0.0), 2)
            # Keep the most recent deal version + rebate rates seen for this country.
            t["deal_version"]   = c.get("deal_version", t["deal_version"])
            t["irish_rebate"]   = c.get("irish_rebate", t["irish_rebate"])
            t["foreign_rebate"] = c.get("foreign_rebate", t["foreign_rebate"])
    return totals


def load_current_week():
    if not CURRENT_WEEK_FILE.exists():
        return None
    with CURRENT_WEEK_FILE.open("r", encoding="utf-8") as f:
        text = f.read()
    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        # A corrupt file (e.g. leftover git conflict markers from a bad
        # merge/stash) must NOT be treated as "no current week" — that used
        # to silently discard every day already logged this week and start
        # a blank file. Fail loudly instead so a human fixes the data.
        raise RuntimeError(
            f"{CURRENT_WEEK_FILE} exists but is not valid JSON ({e}). "
            "Refusing to overwrite it with a fresh week — fix or restore "
            "the file (check for git conflict markers) before rerunning."
        ) from e


def save_current_week(data):
    TAX_DIR.mkdir(parents=True, exist_ok=True)
    with CURRENT_WEEK_FILE.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, separators=(",", ": "))


def archive_week(week_data):
    """Write a completed week to data/tax/weeks/YYYY-MM-DD.json."""
    WEEKS_DIR.mkdir(parents=True, exist_ok=True)
    week_start = week_data.get("week_start", "unknown")
    path = WEEKS_DIR / f"{week_start}.json"
    with path.open("w", encoding="utf-8") as f:
        json.dump(week_data, f, indent=2, separators=(",", ": "))
    log(f"archived week starting {week_start} → {path.name}")


def upsert_day(current, today_iso, country_rows):
    """Replace today's day entry if present, else append it. Then recalc totals."""
    today_entry = {"date": today_iso, "countries": country_rows}
    days = current["days"]
    for i, d in enumerate(days):
        if d.get("date") == today_iso:
            days[i] = today_entry
            log(f"replaced existing entry for {today_iso}")
            break
    else:
        days.append(today_entry)
        log(f"appended new entry for {today_iso}")
    current["totals"] = recalc_totals(days)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    today     = datetime.now(timezone.utc).date()
    today_iso = today.isoformat()
    monday    = this_weeks_monday(today)
    monday_iso = monday.isoformat()

    TAX_DIR.mkdir(parents=True, exist_ok=True)

    # Roll over to a new week if needed
    current = load_current_week()
    if current and current.get("week_start") != monday_iso:
        log(f"new game week — archiving {current['week_start']}")
        archive_week(current)
        current = None
    if current is None:
        current = {"week_start": monday_iso, "days": [], "totals": {}}
        log(f"started week log for {monday_iso}")

    # Skip-if-already-done: if today already has a real (non-empty) entry, a
    # successful run has already happened today. The remaining fallback crons
    # don't need to repeat the work. (An empty/zero entry from an outage run is
    # never written — see the no-data guard below — so this only matches a good
    # reading.)
    for d in current["days"]:
        if d.get("date") == today_iso and d.get("countries"):
            log(f"{today_iso} already logged with data — nothing to do")
            return 0

    # Agreement config (data-driven — see data/tax/deals.json).
    deal_version, deals_by_code, default_deal = load_deals()

    # ── Step 1: Irish citizens ────────────────────────────────────────────────
    log("step 1: fetching Irish citizens…")
    citizens = fetch_all_irish()
    citizen_ids = [c["_id"] for c in citizens if isinstance(c, dict) and c.get("_id")]
    log(f"  {len(citizen_ids)} citizens")
    if not citizen_ids:
        log("no citizens returned — aborting without changes")
        return 1

    # ── Step 2: Owned factories & workers ────────────────────────────────────
    log(f"step 2: fetching factories & workers for {len(citizen_ids)} citizens…")
    factories   = {}   # compId → {compId, compName, itemCode, ownerId, workers, countryId}
    owner_wmap  = {}   # ownerId → {workerId: compId}

    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        for cid, entries in zip(citizen_ids, ex.map(fetch_worker_entries, citizen_ids)):
            for e in entries:
                comp_id = e["compId"]
                if comp_id not in factories:
                    factories[comp_id] = {**e, "countryId": None}
                wmap = owner_wmap.setdefault(cid, {})
                for wid in e["workers"]:
                    wmap[wid] = comp_id

    comp_ids = list(factories.keys())
    owners   = list(owner_wmap.keys())
    log(f"  {len(comp_ids)} factories across {len(owners)} Irish owners")

    if not comp_ids:
        # No factories with workers usually means the API didn't serve worker
        # data (outage) rather than every Irish owner genuinely closing shop.
        # Skip without writing so a fallback cron retries — don't record a
        # blank day.
        log("no Irish-owned factories found (likely API outage) — skipping "
            "write, will retry on the next scheduled run")
        return 0

    # ── Step 3: Factory location → country → income-tax rate ─────────────────
    log("step 3: resolving factory countries & tax rates…")

    regions_obj = trpc("region.getRegionsObject", {}) or {}

    # country.getAllCountries already returns FULL country objects (taxes,
    # code, ...) for all ~180 countries in one ~1s call. We build the map
    # straight from it — NOT via a country.getCountryById per stub. Those ~180
    # extra parallel calls would, under proxy load, fail/retry/time out and get
    # silently dropped, and a dropped country here silently zeroes that
    # country's factories (no tax rate) — corrupting the settlement, not just
    # slowing it. The only field read below is taxes.income, present already.
    all_countries_raw = trpc("country.getAllCountries", {})
    all_countries = (all_countries_raw if isinstance(all_countries_raw, list)
                     else (all_countries_raw or {}).get("items", []))
    country_by_id = {c["_id"]: c for c in all_countries
                     if isinstance(c, dict) and c.get("_id")}
    log(f"  loaded {len(country_by_id)} countries")

    with ThreadPoolExecutor(max_workers=COUNTRY_WORKERS) as ex:
        for comp_id, country_id in ex.map(
            lambda cid: fetch_company_country(cid, regions_obj), comp_ids
        ):
            factories[comp_id]["countryId"] = country_id

    located = sum(1 for f in factories.values() if f.get("countryId"))
    log(f"  located {located}/{len(comp_ids)} factories")

    # ── Step 4: Wages paid in the last 24h, bucketed per worker ──────────────
    log(f"step 4: summing wages paid in last 24h for {len(owners)} owners…")
    worker_wages = {}   # workerId → wages paid in the window

    def fetch_wages_safe(owner_id):
        try:
            return owner_id, fetch_wages_paid(owner_id, owner_wmap[owner_id])
        except Exception as e:
            log(f"  wage fetch error for {owner_id}: {e}")
            return owner_id, {}

    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        for _, by_worker in ex.map(fetch_wages_safe, owners):
            for worker_id, amt in by_worker.items():
                worker_wages[worker_id] = worker_wages.get(worker_id, 0) + amt

    total_wages = sum(worker_wages.values())
    log(f"  total wages observed: {total_wages:.2f}")

    # No-data guard: zero wages across every owner means the API isn't serving
    # transaction data (game outage) — a real active player base never pays
    # nothing in 24h. Don't write a misleading zero day; exit without touching
    # the log so a later fallback cron retries. Today stays blank until a run
    # actually sees wage data.
    if total_wages <= 0:
        log("no wage data observed (likely API outage) — skipping write, "
            "will retry on the next scheduled run")
        return 0

    # ── Step 5: Worker citizenship (Irish vs non-Irish) ──────────────────────
    # Needed to split each worker's tax and apply the right rebate rate, and to
    # count workers per category accurately. Resolve every employed worker (not
    # just the paid ones) so the Irish/foreign head-counts are correct even for
    # workers who happened to earn nothing this window. Owners are Irish citizens
    # by definition, but workers can be from anywhere.
    log("step 5: resolving worker citizenships…")
    all_worker_ids = sorted({wid for f in factories.values() for wid in f["workers"]})
    home_country = {}   # workerId → citizenshipCountryId (None if unresolved → treated non-Irish)
    with ThreadPoolExecutor(max_workers=COUNTRY_WORKERS) as ex:
        for uid, country_id in ex.map(fetch_user_country, all_worker_ids):
            home_country[uid] = country_id
    irish_workers_total = sum(1 for cid in home_country.values() if cid == IRELAND_COUNTRY_ID)
    log(f"  resolved {len(all_worker_ids)} workers ({irish_workers_total} Irish)")

    # ── Aggregate per country (settlement) ───────────────────────────────────
    # Iterate factory → worker so tax is attributed to each worker's citizenship
    # and the host country's agreement. No country-specific logic here: rebate
    # rates come entirely from deals.json (deal_for()).
    agg = {}
    for comp_id in comp_ids:
        f    = factories[comp_id]
        c_id = f.get("countryId")
        c    = country_by_id.get(c_id) if c_id else None
        if not c:
            continue
        rate = float((c.get("taxes") or {}).get("income") or 0)
        code = c.get("code") or c.get("iso")
        deal = deal_for(code, deals_by_code, default_deal)
        if c_id not in agg:
            agg[c_id] = {
                "id":                 c_id,
                "name":               c.get("name", "—"),
                "code":               code,
                "rate":               rate,
                "factories":          0,
                "workers":            0,
                "irish_workers":      0,
                "foreign_workers":    0,
                "wages":              0.0,
                "tax":                0.0,
                "irish_worker_tax":   0.0,
                "foreign_worker_tax": 0.0,
                "manual_rebate_due":  0.0,
                "host_retained":      0.0,
                # This country's own rebate rates, baked in so a per-country
                # consumer (e.g. the partner view) never needs the full
                # deals.json (which lists every country's agreement).
                "irish_rebate":       deal["irishRebate"],
                "foreign_rebate":     deal["foreignRebate"],
                "deal_version":       deal_version,
            }
        a = agg[c_id]
        a["factories"] += 1
        a["workers"]   += len(f["workers"])
        for wid in f["workers"]:
            wages = float(worker_wages.get(wid, 0))
            a["wages"] += wages
            tax = wages * (rate / 100)
            a["tax"]   += tax
            if home_country.get(wid) == IRELAND_COUNTRY_ID:
                a["irish_workers"]     += 1
                a["irish_worker_tax"]  += tax
                a["manual_rebate_due"] += tax * deal["irishRebate"]
            else:
                a["foreign_workers"]    += 1
                a["foreign_worker_tax"] += tax
                a["manual_rebate_due"]  += tax * deal["foreignRebate"]
        # Host country keeps: gross − automatic 30% remittance − manual rebate.
        a["host_retained"] = a["tax"] * (1 - AUTO_REMIT) - a["manual_rebate_due"]

    # Round the accumulated floats once, at the end.
    for a in agg.values():
        for k in ("wages", "tax", "irish_worker_tax", "foreign_worker_tax",
                  "manual_rebate_due", "host_retained"):
            a[k] = round(a[k], 2)

    # Rank by settlement owed to Ireland first, then gross tax as a tiebreaker.
    country_rows = sorted(agg.values(), key=lambda x: (-x["manual_rebate_due"], -x["tax"]))
    total_tax    = sum(r["tax"] for r in country_rows)
    total_rebate = sum(r["manual_rebate_due"] for r in country_rows)
    log(f"  gross daily tax: {total_tax:.2f} · settlement due to Ireland: "
        f"{total_rebate:.2f} across {len(country_rows)} countries")
    for r in sorted(country_rows, key=lambda x: -x["manual_rebate_due"])[:5]:
        log(f"    {r['name']:20s}  gross={r['tax']:.2f}  rebate={r['manual_rebate_due']:.2f}")

    # ── Save ──────────────────────────────────────────────────────────────────
    upsert_day(current, today_iso, country_rows)
    save_current_week(current)
    log("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
